management:
  health:
    redis:
      enabled: false  # Redis 헬스체크만 비활성화
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always  # 상세 정보 표시

spring:
  application:
    name: service-batch
  profiles:
    active: local
    group:
      local: local
      test: test
      dev: dev
      prod: prod
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
      log-condition-evaluation-delta: false
  jpa:
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      WRITE_DATES_AS_TIMESTAMPS: false
  data:
    redis:
      repositories:
        enabled: false
    jpa:
      repositories:
        enabled: false
