server:
  port: 30180


eureka:
  client:
    service-url:
      defaultZone: http://localhost:30210/eureka/  # 유레카 서버 주소
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  batch:
    jdbc:
      initialize-schema: always
  test:
    database:
      replace: any
